name: Web Calculator

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: build image
        run: docker build -t web-calaculator .

      - name: container run
        run: docker run -dt --name web-calaculator -p 8080:8080 web-calaculator

      - name : list
        run: docker ps -a
   

      - name: CURL 200 Status Check
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
          echo "HTTP Status Code: $STATUS"
          if [ "$STATUS" -eq 200 ]; then
          echo " CURL request successful - HTTP 200"
          else
          echo "CURL request failed - HTTP $STATUS"
          exit 1
          fi
  success_notification:
    needs: test
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name:  success
        run: echo "success mail sent to team"
  failure_notification:
    needs: test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: failure
        run: echo "failure mail sent to team"  

        
        

        
