name: Web Calculator

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: build image
        run: docker build -t web-calaculator .

      - name: container run
        run: docker run -dt --name web-calaculator -p 8080:80 web-calaculator

      - name : list
        run: docker ps -a

        
